# Railway monorepo configuration for SMILe Sales Funnel
# Defines 3 services: worker, api, ui

[build]
builder = "DOCKERFILE"

# Worker service (Python FastAPI)
[service.worker]
dockerfilePath = "Dockerfile.worker"
autoDeploy = true

# API service (NestJS)
[service.api]
dockerfilePath = "Dockerfile.api"
autoDeploy = true

# UI service (React+Vite)
[service.ui]
dockerfilePath = "Dockerfile.ui"
autoDeploy = true
