# Railway monorepo configuration for SMILe Sales Funnel
# Defines 3 services: worker, api, ui

[service.worker]
rootDir = "worker"
dockerfilePath = "worker/Dockerfile"

[service.api]
rootDir = "api"
dockerfilePath = "api/Dockerfile"

[service.ui]
rootDir = "ui"
dockerfilePath = "ui/Dockerfile"
