# Railway monorepo configuration for SMILe Sales Funnel
# Defines 3 services: worker, api, ui

[service.worker]
root = "worker"
dockerfilePath = "worker/Dockerfile"
autoDeploy = true

[service.api]
root = "api"
dockerfilePath = "api/Dockerfile"
autoDeploy = true

[service.ui]
root = "ui"
dockerfilePath = "ui/Dockerfile"
autoDeploy = true